### ISSUE TITLE
yearsExperienceFromBeginningOf is hardcoded with year.

### ISSUE THREAD

**Issue by coquizen** [learn-co-curriculum/js-object-oriented-classes-travel-lab#10]
This test fails if the current year later than 2017. It should not be hardcoded with 2017

**Comment by morgvanny** [comment]
Hi! The date is actually hardcoded intentionally, in order to calculate an exact amount of time from a start and end date - but 22 for the expected answer was incorrect and has been reverted back to 21. Thanks for letting us know!
