### ISSUE TITLE
date is hardcoded

### ISSUE THREAD

**Issue by squamuglia** [learn-co-curriculum/js-object-oriented-classes-travel-lab#11]
`describe('yearsExperienceFromBeginningOf', function() {
    it('calculates the number of years driven given an endDate', function() {
      expect(driver.yearsExperienceFromBeginningOf(2017)).to.equal(22)
    })
  })`

date should be dynamic `(new Date).getFullYear`

**Comment by morgvanny** [comment]
Hi! The date is actually hardcoded intentionally, in order to calculate an exact amount of time from a start and end date - but 22 was incorrect and has been reverted back to 21. Thanks for letting us know!
