### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by arianaberger** [learn-co-curriculum/js-object-oriented-classes-travel-lab#13]
A route is initialized with two arguments, a beginningLocation and an endingLocation. Both of these arguments are JavaScript objects with **an attributes** of horizontal and vertical.

>> should be either "with attributes of" or "with an attribute of"

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @arianaberger.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
