### ISSUE TITLE
Grammar issue

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/js-object-oriented-classes-travel-lab#14]
The grammar issue is starred below:
To calculate the distance **of in** streets, you can use subtraction (eg. 13th street to 10th street is three blocks). To calculate the distance **of** avenues travelled, you will need to know the names and order of avenues in New York City. 

My suggestion would be to change both to just "in."

Thank you.

**Comment by drakeltheryuujin** [comment]
We have updated the materials and fixed the grammatical errors.
