### ISSUE TITLE
missing word in README

### ISSUE THREAD

**Issue by logemerson** [learn-co-curriculum/js-object-oriented-classes-travel-lab#5]
<img width="516" alt="screen shot 2017-11-06 at 1 51 20 pm" src="https://user-images.githubusercontent.com/28125427/32458193-981acb22-c2f9-11e7-9a22-8998ee664a6a.png">

The word "know" is missing from the highlighted sentence. That is, "you will need to the names and order of avenues" should be "you will need _know_ to the names and order of avenues".

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We corrected the readme.

As always thank you for contributing!
