### ISSUE TITLE
Update year on line 21 of indexTest.js to 2018

### ISSUE THREAD

**Issue by BuffaloRob** [learn-co-curriculum/js-object-oriented-classes-travel-lab#8]
test won't pass unless year is changed to 2018, will equal 21 instead of expected 22

**Comment by morgvanny** [comment]
I think we're keeping it at 2017, and changing it back to expect 21. That way there's a consistent start date and end date to calculate with, so it should be 21 forever, regardless of what the current year is. Thanks for letting us know!
