### ISSUE TITLE
It doesn't test if travel occurs in opposite directions

### ISSUE THREAD

**Issue by morgvanny** [learn-co-curriculum/js-object-oriented-classes-travel-lab#9]
One could conceivably get lucky and pass the tests, even if their code doesn't account for traveling south, for example, because the tests only check for vertical distance when traveling north. It would make sense to have additional tests in which travel occurs when traveling south, west, or both (ensuring no negative numbers are allowed for distance travelled).

**Comment by jenmyers** [comment]
Hello!

We're always working to improve the curriculum. This is helpful feedback and we'll take it into consideration as we make future updates. Thank you for taking your time to help us make Learn a better place.
